import type { Scenario, Thread } from './types'

export const scenarios: Scenario[] = [
  { eyebrow: 'Scenario 01 · The quiet disagreement', title: 'A decision you know will disappoint someone', body: 'You lead a small team. A deadline is approaching, and one proposed shortcut would protect delivery but create hidden work for a colleague who is already stretched.', context: 'The shortcut is reversible. The colleague has not been asked yet. Your manager values the deadline more than process perfection.', question: 'What would you do, and what would matter most in that moment?', reason: 'A baseline situation to notice what you protect when values pull in different directions.' },
  { eyebrow: 'Scenario 02 · The changed condition', title: 'The same shortcut now carries your name', body: 'The deadline is still approaching, but you discover that the hidden work will land on you. Taking it on would preserve your colleague’s focus and make your own week considerably harder.', context: 'No one will know whether you absorb the cost. You could still ask for help, but that would expose the original shortcut.', question: 'How does the personal cost change your decision, if at all?', reason: 'Testing whether your principle changes when the burden moves closer to you.' },
  { eyebrow: 'Scenario 03 · The role reversal', title: 'You are the person downstream', body: 'You join a project late and learn that an earlier decision created hidden work for you. The person who made it had a reasonable deadline and never intended to create harm.', context: 'You can quietly fix the issue, raise it with the team, or ask the original decision-maker to help repair it.', question: 'What would you want from the person who made that decision?', reason: 'Reversing the role to compare the care you offer with the care you expect.' },
  { eyebrow: 'Scenario 04 · The unresolved tension', title: 'When care begins to slow everyone down', body: 'A teammate repeatedly needs more context before acting. You can keep adapting the process around them, or set a firmer expectation that they make reasonable decisions with incomplete information.', context: 'They are learning quickly, but the rest of the team is beginning to carry the cost of every delay.', question: 'Where would you draw the line between patience and accountability?', reason: 'Putting two emerging considerations into direct conflict without forcing a clean answer.' },
  { eyebrow: 'Scenario 05 · Transfer', title: 'A difficult truth in a different room', body: 'A close friend asks whether you think they should accept an opportunity that looks impressive but would move them away from the people and routines that keep them well.', context: 'They want encouragement, but they have not asked for a decision. You know only part of the situation.', question: 'How would you respond without taking the decision away from them?', reason: 'Transferring the practice from work into a relationship with a different kind of responsibility.' },
]

export const fixtureThreads: Thread[] = [
  { title: 'You look for the human cost inside an efficient decision.', description: 'You appear to weigh downstream burden alongside visible delivery outcomes.', status: 'tentative', evidence: 'From this response' },
  { title: 'You prefer reversible action when uncertainty is high.', description: 'You may be more willing to act when a decision can be revisited without lasting harm.', status: 'tentative', evidence: 'From this response' },
]

export const initialTension = 'Efficiency and care may both matter to you.'
