import type { Probe } from '../domain/types'

type Props = { probe: Probe; response: string; simulationResponse: string; setSimulationResponse: (value: string) => void; transferNote: string; setTransferNote: (value: string) => void; onSave: () => void }

export function Explore({ probe, response, simulationResponse, setSimulationResponse, transferNote, setTransferNote, onSave }: Props) {
  const hasSimulation = simulationResponse.trim().length > 20
  return <section className="explore-page page-narrow">
    <button className="back-button" onClick={onSave}>← Keep the lived account and return</button>
    <div className="explore-header"><div><p className="kicker">Model-guided exploration · {probe.dimension}</p><h2>Change one thing. Notice what moves.</h2><p> This is a constructed situation, not a prediction or a test. Use it to observe a possible response and then decide whether it connects back to your life.</p></div><div className="explore-source"><span>01</span><p><strong>Why this direction</strong>{probe.rationale}</p></div></div>
    <div className="simulation-card"><div className="section-label"><span>Constructed situation</span><span>Text practice</span></div><h3>{probe.title}</h3><p className="simulation-prompt">{probe.prompt}</p><label htmlFor="simulation-response">What do you notice yourself saying, doing, feeling, or protecting?</label><textarea id="simulation-response" value={simulationResponse} onChange={(event) => setSimulationResponse(event.target.value)} placeholder="Respond as if you are inside the situation…" /><div className="simulation-footer"><span>{simulationResponse.length ? `${simulationResponse.length} characters` : 'There is no preferred response.'}</span>{!hasSimulation && <span>Write a little more to compare the two situations.</span>}</div></div>
    {hasSimulation && <div className="transfer-card"><div className="section-label"><span>02 / Transfer back</span><span>Keep the distinction open</span></div><h3>Does this touch the lived situation?</h3><p>Compare the constructed response with what you described earlier. It may connect, differ, or reveal that the model's direction is not useful.</p><div className="compare-grid"><div><span className="section-label">Lived account</span><blockquote>“{response}”</blockquote></div><div><span className="section-label">Constructed response</span><blockquote>“{simulationResponse}”</blockquote></div></div><label htmlFor="transfer-note">What, if anything, do you want the model to carry forward?</label><textarea id="transfer-note" value={transferNote} onChange={(event) => setTransferNote(event.target.value)} placeholder="A similarity, difference, question, exception, or connection…" /><button className="primary-button" onClick={onSave}>Keep this exploration <span>→</span></button></div>}
  </section>
}
