import type { JourneyModel } from '../domain/types'

type Props = { draft: string; setDraft: (value: string) => void; model?: JourneyModel; isReflecting: boolean; apiError: string; onGenerate: () => void; onBack: () => void }

export function Journey({ draft, setDraft, model, isReflecting, apiError, onGenerate, onBack }: Props) {
  return <section className="story-page page-narrow"><div className="story-hero"><div><button className="back-button" onClick={onBack}>← Home</button><p className="kicker">A longer practice</p><h2>See how your way of meeting life has changed.</h2><p className="story-lede">Paste a long-form account of your life or work. Room to Respond will organise it into contexts, episodes, faculties, changes, and open questions.</p></div><div className="story-boundary"><span>◌</span><p><strong>Your account stays yours.</strong> This text is sent only when you ask for a model. Edit the result before using it anywhere else.</p></div></div><div className="story-workspace"><div className="story-input"><div className="section-label"><span>Private source</span><span>{draft.length} characters</span></div><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write or paste the situations, transitions, choices, and changes you want to examine…" /><div className="story-input-footer"><span>Include what happened, what you felt, thought, said, did, wanted, and learned. You can leave anything out.</span><button className="primary-button" disabled={draft.trim().length < 120 || isReflecting} onClick={onGenerate}>{isReflecting ? 'Building the model…' : 'Build my evolution model'} <span>→</span></button></div></div>{apiError && <div className="model-notice">◌ {apiError}</div>}{model && <JourneyOutput model={model} />}</div></section>
}

function JourneyOutput({ model }: { model: JourneyModel }) {
  return <div className="story-output"><div className="story-output-head"><div><p className="kicker">Reviewable evolution model</p><h3>{model.thesis}</h3></div><span className="story-status">Provisional · edit before sharing</span></div><div className="story-direction"><span className="section-label">The thread to examine</span><p>Look for how context changes the faculties involved, which strategies emerge, and where the account still needs another person's perspective.</p></div><div className="evolution-timeline">{model.periods.map((period, index) => <article key={`${period.label}-${index}`}><span className="timeline-marker" /><span className="section-label">{period.label} · {period.faculties.join(' · ')}</span><h4>{period.turningPoint}</h4><p><strong>Context:</strong> {period.context}</p><p><strong>Possible shift:</strong> {period.shift}</p><small className="thread-evidence">↳ {period.evidence}</small></article>)}</div><div className="story-patterns"><span className="section-label">What may be evolving</span>{model.evolution.map((item) => <article key={item}><p>{item}</p><span className="status status-tentative">Hypothesis</span></article>)}</div><div className="story-followups"><span className="section-label">Open questions</span><ul>{model.openQuestions.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="interview-output"><span className="section-label">A concise version to edit</span><textarea className="interview-editor" defaultValue={model.interviewNarrative} aria-label="Editable interview narrative" /><p className="sharing-note">This is a draft transformation, not the authoritative version of your life. Keep only what is accurate, useful, and appropriate for the person in front of you.</p></div></div>
}
