import type { JourneyMode, JourneyModel } from '../domain/types'

type Props = { draft: string; setDraft: (value: string) => void; mode: JourneyMode; setMode: (value: JourneyMode) => void; model?: JourneyModel; isReflecting: boolean; apiError: string; onGenerate: () => void; onBack: () => void }

const modes: { value: JourneyMode; label: string; description: string }[] = [
  { value: 'single-event', label: 'One event', description: 'One moment in detail' },
  { value: 'one-situation', label: 'One situation', description: 'Several events in one context' },
  { value: 'multiple-situations', label: 'Several situations', description: 'Different contexts across time' },
]

function placeholderFor(mode: JourneyMode): string {
  if (mode === 'single-event') return 'Describe one event: what happened, what you felt, thought, said, did, wanted, and noticed afterward…'
  if (mode === 'one-situation') return 'Describe several moments within one situation, relationship, role, or transition. Show what changed from one moment to the next…'
  return 'Describe several situations across your life or work. Include the sequence, transitions, choices, and changes you want to examine…'
}

export function Journey({ draft, setDraft, mode, setMode, model, isReflecting, apiError, onGenerate, onBack }: Props) {
  return <section className="story-page page-narrow"><div className="story-hero"><div><button className="back-button" onClick={onBack}>← Home</button><p className="kicker">A private account map</p><h2>Choose how to read what you bring in.</h2><p className="story-lede">Use one text box for one event, several events in one situation, or several situations across time.</p></div><div className="story-boundary"><span>◌</span><p><strong>Your account stays yours.</strong> This text is sent only when you ask for a model. Edit the result before using it anywhere else.</p></div></div><div className="story-workspace"><div className="story-input"><div className="section-label"><span>How much are you bringing in?</span><span>{draft.length} characters</span></div><div className="story-config" role="group" aria-label="Account scope">{modes.map((item) => <button key={item.value} className={mode === item.value ? 'selected' : ''} onClick={() => setMode(item.value)}><strong>{item.label}</strong><small>{item.description}</small></button>)}</div><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={placeholderFor(mode)} /><div className="story-input-footer"><span>Write in your own words. Include what happened, what you felt, thought, said, did, wanted, and learned where useful.</span><button className="primary-button" disabled={draft.trim().length < 120 || isReflecting} onClick={onGenerate}>{isReflecting ? 'Building the map…' : 'Build the account map'} <span>→</span></button></div></div>{apiError && <div className="model-notice">◌ {apiError}</div>}{model && <JourneyOutput model={model} />}</div></section>
}

function JourneyOutput({ model }: { model: JourneyModel }) {
  return <div className="story-output"><div className="story-output-head"><div><p className="kicker">Reviewable account map</p><h3>{model.thesis}</h3></div><span className="story-status">Provisional · edit before sharing</span></div><div className="story-direction"><span className="section-label">How to read this</span><p>Look for what happened, which faculties were involved, what changed with context, and which questions still need another person's perspective.</p></div><div className="evolution-timeline">{model.periods.map((period, index) => <article key={`${period.label}-${index}`}><span className="timeline-marker" /><span className="section-label">{period.label} · {period.faculties.join(' · ')}</span><h4>{period.turningPoint}</h4><p><strong>Context:</strong> {period.context}</p><p><strong>Possible shift:</strong> {period.shift}</p><small className="thread-evidence">↳ {period.evidence}</small></article>)}</div><div className="story-patterns"><span className="section-label">What may be evolving</span>{model.evolution.map((item) => <article key={item}><p>{item}</p><span className="status status-tentative">Hypothesis</span></article>)}</div><div className="story-followups"><span className="section-label">Open questions</span><ul>{model.openQuestions.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="interview-output"><span className="section-label">A concise version to edit</span><textarea className="interview-editor" defaultValue={model.interviewNarrative} aria-label="Editable interview narrative" /><p className="sharing-note">This is a draft transformation, not the authoritative version of your life. Keep only what is accurate, useful, and appropriate for the person in front of you.</p></div></div>
}
