import type { ExperienceDetails, Scenario } from '../domain/types'

type Props = { response: string; setResponse: (value: string) => void; details: ExperienceDetails; setDetails: (details: ExperienceDetails) => void; scenario: Scenario; showContext: boolean; setShowContext: (value: boolean) => void; onSubmit: () => void; isReflecting: boolean }

export function Respond({ response, setResponse, details, setDetails, scenario, showContext, setShowContext, onSubmit, isReflecting }: Props) {
  const update = (key: keyof ExperienceDetails, value: string) => setDetails({ ...details, [key]: value })
  return <section className="practice page-grid">
    <div className="scenario-column"><p className="kicker">{scenario.eyebrow}</p><h2>{scenario.title}</h2><p className="scenario-body">{scenario.body}</p><button className="context-toggle" onClick={() => setShowContext(!showContext)}><span>{showContext ? '−' : '+'}</span> Additional context</button>{showContext && <p className="context-copy">{scenario.context}</p>}<div className="selection-note"><span className="selection-icon">✦</span><div><strong>Why this prompt</strong><p>{scenario.reason}</p></div></div></div>
    <div className="response-column"><div className="response-heading"><p className="kicker">Your lived account</p><span>Private · autosaved</span></div><h3>{scenario.question}</h3><textarea autoFocus value={response} onChange={(event) => setResponse(event.target.value)} placeholder="Start with what happened, in your own words…" /><details className="experience-details"><summary>Add what was happening inside the moment</summary><p>These prompts help the model stay close to the sequence of your experience. Leave anything blank that does not feel useful.</p><div className="detail-grid">{([['felt', 'What did you feel or notice in your body?'], ['thought', 'What were you thinking or assuming?'], ['said', 'What did you say, or hold back?'], ['did', 'What did you do next?'], ['wanted', 'What did you want, need, or protect?'], ['consequence', 'What happened afterward?'], ['now', 'What do you think about it now?']] as Array<[keyof ExperienceDetails, string]>).map(([key, label]) => <label key={key}>{label}<textarea value={details[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div></details><div className="response-footer"><span>{isReflecting ? 'Looking for a careful next question…' : response.length > 0 ? `${response.length} characters` : 'Take your time'}</span><button className="primary-button" disabled={response.trim().length < 20 || isReflecting} onClick={onSubmit}>{isReflecting ? 'Finding a thread…' : 'Find a thread to explore'} <span>→</span></button></div></div>
  </section>
}
