import type { Reflection, Synthesis, Thread } from '../domain/types'
import { scenarios } from '../domain/scenarios'

type Props = { threads: Thread[]; tension: string; synthesis?: Synthesis; history: Reflection[]; selectedReflectionId: number | null; isComplete: boolean; onBack: () => void; onNext: () => void; onOpenScenario: (id: number) => void }

export function Threads({ threads, tension, synthesis, history, selectedReflectionId, isComplete, onBack, onNext, onOpenScenario }: Props) {
  const selected = selectedReflectionId === null ? undefined : history.find((entry) => entry.id === selectedReflectionId)
  if (selected) return <section className="threads-page page-narrow"><ScenarioDetail selected={selected} onBack={onBack} /></section>

  return <section className="threads-page page-narrow"><div className="threads-header"><div><p className="kicker">Your evolving model</p><h2>Threads, not labels.</h2><p>One synthesized model at the top. The scenarios below are the evidence that lets it change.</p></div>{!isComplete && <button className="primary-button" onClick={onNext}>Next practice <span>→</span></button>}</div><Evolution synthesis={synthesis} history={history} threads={threads} tension={tension} /><div className="scenario-evidence"><div className="section-label"><span>Scenario evidence</span><span>{history.length} of {scenarios.length} completed</span></div>{history.length === 0 ? <p className="empty-copy">Complete a scenario and its threads will appear here as evidence for your evolving model.</p> : history.slice().reverse().map((entry) => <button className="scenario-evidence-row" key={entry.id} onClick={() => onOpenScenario(entry.id)}><span className="thread-number">{entry.scenario.eyebrow.split('·')[0].trim().replace('Scenario ', '')}</span><span><strong>{entry.scenario.title}</strong><small>{entry.threads.length} threads · {entry.correction ? 'correction added' : 'no correction added'}</small></span><span>→</span></button>)}</div>{isComplete ? <div className="completion-note"><span>✦</span><div><strong>Five-scenario journey complete.</strong><p>Your next step is to review the connections above and the evidence below. A new practice cycle can be designed after this model has been reviewed.</p></div></div> : history.length > 0 && <button className="back-button" onClick={onBack}>← Back to current reflection</button>}</section>
}

function Evolution({ synthesis, history, threads, tension }: { synthesis?: Synthesis; history: Reflection[]; threads: Thread[]; tension: string }) {
  const summary = synthesis?.summary ?? (history.length ? 'Your first reflection is now a starting point. Complete another scenario to see what repeats, changes, or depends on context.' : 'Complete your first scenario to begin building a synthesized model.')
  const recurring = synthesis?.recurringThemes ?? (history.length ? ['No recurring pattern yet'] : ['Your first response will give the model its first signal.'])
  const changes = synthesis?.changes ?? (history.length ? ['More scenarios will give this model something to compare.'] : ['The model will become more useful as you test it against context.'])
  const connections = synthesis?.connections ?? (history.length ? ['Each scenario will remain available as evidence.'] : ['Connections appear after the next reflection.'])
  return <div className="evolution-panel"><div className="evolution-heading"><p className="kicker">{history.length > 1 ? 'Your synthesized model' : 'The first signal'}</p><h3>{summary}</h3><p>The point is not a score. It is seeing what repeats, what changes, and what depends on the situation.</p></div><div className="evolution-columns"><ProfileColumn label="Recurring threads" items={recurring} /><ProfileColumn label="What may be changing" items={changes} /><ProfileColumn label="Connections" items={connections} /></div>{history.length === 1 && <div className="model-notice">◌ This model is intentionally provisional. It currently reflects one scenario, one response, and {threads.length} tentative thread{threads.length === 1 ? '' : 's'}.</div>}{history.length > 0 && <div className="tension-box"><span className="tension-mark">∿</span><div><p className="kicker">Current tension</p><h3>{tension}</h3></div></div>}</div>
}

function ProfileColumn({ label, items }: { label: string; items: string[] }) { return <div><span className="section-label">{label}</span><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div> }

function ScenarioDetail({ selected, onBack }: { selected: Reflection; onBack: () => void }) { return <div className="scenario-detail"><button className="back-button" onClick={onBack}>← Back to synthesized model</button><p className="kicker">{selected.scenario.eyebrow}</p><h2>{selected.scenario.title}</h2><div className="selected-response"><span className="section-label">Original response</span><blockquote>“{selected.response}”</blockquote></div><div className="thread-overview">{selected.threads.map((thread, index) => <article className="overview-row" key={`${thread.title}-${index}`}><span className="thread-number">0{index + 1}</span><div><h3>{thread.title}</h3><p>{thread.description}</p><span className="thread-evidence">↳ {thread.evidence}</span></div><span className={`status status-${thread.status}`}>{thread.status}</span></article>)}</div><div className="tension-box"><span className="tension-mark">∿</span><div><p className="kicker">Unresolved tension</p><h3>{selected.tension}</h3><p>This tension remains connected to the original scenario and response.</p></div></div></div> }
